version: '3'
services:
    server: 
        build: .
        ports: 
            - 8000:3000
        links:
            - db:db
        depends_on:
            - db
    db:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: 'psql'
        ports: 
            - 2000:5432